Repository BCG-X-Official/fluxus, pull requests merged in 2024-07, with the labels that each got.

#25 FIX: Accept Iterable of Mappings from async step functions in functional API
  RELEASE_NOTES.rst
  condabuild/meta.yaml
  pyproject.toml
  src/fluxus/functional/_functions.py
  src/fluxus/functional/conduit/_step.py
  test/fluxus_test/test_functional.py
  tox.ini
Labels: bug

#22 BUILD: update veracode job condition and remove dependency
  .github/workflows/fluxus-release-pipeline.yaml
Labels: build

#27 DOC: update contributor guide
  CONTRIBUTING.md
  sphinx/source/contributor_guide/index.rst
Labels: documentation

#26 BUILD: release fluxus 1.0.2
  .github/workflows/fluxus-release-pipeline.yaml
  .idea/fluxus.iml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  RELEASE_NOTES.rst
  condabuild/meta.yaml
  pyproject.toml
  sphinx/source/contributor_guide/index.rst
  src/fluxus/__init__.py
  src/fluxus/functional/_functions.py
  src/fluxus/functional/conduit/_step.py
  test/fluxus_test/test_functional.py
  tox.ini
Labels: build

#29 FIX: Always use buffered producers to allow multiple concurrent flow paths to use the same products
  .pre-commit-config.yaml
  src/fluxus/_passthrough.py
  src/fluxus/_transformer.py
  src/fluxus/core/_base.py
  src/fluxus/core/_chained_base_.py
  src/fluxus/core/_concurrent.py
  src/fluxus/core/_conduit.py
  src/fluxus/core/producer/_chained_.py
  src/fluxus/core/producer/_producer_base.py
  src/fluxus/core/producer/_simple.py
  src/fluxus/core/transformer/_chained_.py
  src/fluxus/core/transformer/_simple.py
  src/fluxus/core/transformer/_transformer_base.py
  src/fluxus/viz/_graph.py
  test/fluxus_test/test_flow.py
Labels: bug, refactor

#28 BUILD: update release pipeline
  .github/workflows/fluxus-release-pipeline.yaml
  RELEASE_NOTES.rst
  src/fluxus/__init__.py
Labels: enhancement

#30 BUILD: Release fluxus 1.0.3
  .github/workflows/fluxus-release-pipeline.yaml
  .pre-commit-config.yaml
  RELEASE_NOTES.rst
  src/fluxus/_passthrough.py
  src/fluxus/_transformer.py
  src/fluxus/core/_base.py
  src/fluxus/core/_chained_base_.py
  src/fluxus/core/_concurrent.py
  src/fluxus/core/_conduit.py
  src/fluxus/core/producer/_chained_.py
  src/fluxus/core/producer/_producer_base.py
  src/fluxus/core/producer/_simple.py
  src/fluxus/core/transformer/_chained_.py
  src/fluxus/core/transformer/_simple.py
  src/fluxus/core/transformer/_transformer_base.py
  src/fluxus/viz/_graph.py
  test/fluxus_test/test_flow.py
Labels: build
